# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.12.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for NixOS configs ❄️
devcontainername: nixos
docs: false
imagename: devcontainers/nixos
registry: true
releases: true
reponame: devcontainer-nixos
repourl: https://github.com/radio-aktywne/devcontainer-nixos
